lang: fr
theme: jekyll-theme-minimal
title: vaccin.click
logo: logo.svg
show_downloads: false

# jekyll-multiple-languages-plugin specific settings: https://github.com/kurtsson/jekyll-multiple-languages-plugin#4-configuration
languages: ["fr", "de"]
