name: Lint the project

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Lint the web extension
        run: npx web-ext lint

      - name: Check code style
        run: npm run lint

      - name: Build the extension
        run: npm run build
