name: Lint the project

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint the web extension
        run: npx web-ext lint -w

      - name: Check CS
        run: npx prettier --check .
